#ifndef CONSTANTS_H
#define CONSTANTS_H

#include "Material.h"

constexpr int MAX_X = 20;
constexpr int MIN_X = -20;

constexpr int MAX_Z = 20;
constexpr int MIN_Z = -20;

// WINDOW DEFINE(s)
#define FPS60 1.0f/60.0f
#define MINTOL 0.0001

// RESTITUTION COEFFICIENT DEFINE(s)
#define RESTCCOEF_SILICON 1.79
#define RESTCCOEF_ALUMINA 1.24
#define RESTCCOEF_STAINLESS_STEEL 1.0
#define RESTCCOEF_TUNGSTEN 0.37
#define RESTCCOEF_LEAD 0.08
#define RESTCCOEF_ALUMINUM 0.1
#define RESTCCOEF_COPPER 0.15
#define RESTCCOEF_NICKEL 0.15
#define RESTCCOEF_ZINC 0.21

// FRICTION COEFFICIENT DEFINE(s)
#define FRICCOEF_GRAPHIRE 0.1
#define FRICCOEF_PHOSPHOR_BRONZE 0.35
#define FRICCOEF_CAST_IRON 0.4
#define FRICCOEF_ACRYLIC 0.5
#define FRICCOEF_COPPER 0.53
#define FRICCOEF_BRASS 0.51
#define FRICCOEF_ALUMINUM 0.61
#define FRICCOEF_GLASS 0.9
#define FRICCOEF_DIAMOND 0.1

#endif
